# Generated by Django 4.2.7 on 2023-12-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_delete_education'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='work',
            table='work',
        ),
    ]
