# Generated by Django 4.2.7 on 2024-03-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
