# Generated by Django 4.2.7 on 2023-12-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='education',
            table='education',
        ),
    ]
