# Generated by Django 4.2.7 on 2024-01-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='highlight',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, upload_to='skill_logo/'),
        ),
    ]
