# Generated by Django 4.2.7 on 2024-03-18 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('award_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('awarded_by', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'awards',
            },
        ),
    ]
