# Generated by Django 4.2.7 on 2023-12-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='award',
            table='awards',
        ),
    ]
